config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  ActiveAdmin.routes(self)
  root 'welcome#index'
  get '/coming_soon', to: 'welcome#coming_soon', as: 'coming_soon'

  get 'user/sign_in', to: 'sessions#sign_in', as: "sign_in"
  get "/auth/auth0/callback", to: 'sessions#callback' #lock callback
  get "/auth/failure", to: 'sessions#failure'
  post '/initial_settings', to: 'sessions#initial_settings'
  post '/change_language', to: 'sessions#change_language'
  post '/change_state', to: 'sessions#change_state'
  delete '/logout', to: 'sessions#log_out'
  
  scope module: 'api' do
    get 'api/jobs/search_by_id', to: 'jobs#search_by_id'
    get '/state/:state_id/:state_name/jobs', to: 'jobs#index', as: 'api_jobs'
    get '/api/jobs', to: 'jobs#index', as: 'api_render_jobs'
    get '/api/jobs/autocomplete/where', to: 'jobs#autocomplete_where'
    get '/api/jobs/autocomplete/what', to: 'jobs#autocomplete_what'
    get 'api/business_on_sales/suggestions', to: 'business_on_sales#suggestions'
    get 'api/business_on_sales/salons', to: 'business_on_sales#search'
    post 'api/business_on_sales', to: 'business_on_sales#create'
    get 'api/business_on_sales/cities', to: 'business_on_sales#fetch_cities'
    get 'api/business_on_sales/update_views', to: 'business_on_sales#update_view'
    get 'api/features/jobs', to: 'features#get_featured_jobs'
    get 'api/features/business_on_sales', to: 'features#get_featured_business_on_sales'
    get 'api/used_items/search', to: 'used_items#search'
    get 'api/used_items/suggestions', to: 'used_items#suggestions'
  end

  resources :jobs, only: [:show, :index, :create] do
    collection do
      get '/state/:state_name/:state_id/choose_company', to: 'jobs#choose_company_location', as: 'choose_company_location'
      get '/state/:state_name/:state_id/location/:location_id', to: 'jobs#new', as: 'new'
      
      get '/choose_state', to: 'jobs#choose_state', as: 'choose_state'
    end
  end
  
  resources :business_on_sales, only: [:new, :index]
  resources :states do
    resources :used_items, only: [:index]
  end
  resources :subscriptions, only: :create
  resources :plans, only: [:show] do 
    collection do
      get 'choose_plan', to: 'plans#display_plans', as: 'choose' #choose_plans_path
      get 'choose_business_on_sale_plan', to: 'plans#display_business_on_sale_plans', as: 'choose_business_on_sale' #choose_plans_path
    end
  end

  resources :states, only: [:index] do #state index for yellow page
  	resources :companies, path: :nail_salons, only: [:index, :show, :create] #you can only have a list by states/companies
  end 
  resources :users, only: [] do #for now
  	resources :companies, { path: :nail_salons } #ALL CRUD of companies + company_states happens under USER
  end

  scope module: 'stripe' do
    get '/checkout', to: 'subscriptions#new'
    post '/checkout_callback', to: 'subscriptions#create'
    get 'thank_you', to: 'subscriptions#thank_you', as: 'thank_you'
  end

end

app/models/job.rb
class Job < ActiveRecord::Base
  searchkick merge_mappings: true, mappings: {
    job: {
      properties: {
        created_at: {
          type: 'date'
        }
      }
    }
  }
 # searchkick merge_mappings: true, mappings: {job:
 #  {"_all"=>{"analyzer"=>"searchkick_text_start_index"},
 #   "dynamic_templates"=>
 #    [{"string_template"=>
 #       {"match"=>"*",
 #        "match_mapping_type"=>"string",
 #        "mapping"=>{"fields"=>{"analyzed"=>{"index"=>"analyzed", "type"=>"text"}}, "ignore_above"=>256, "include_in_all"=>true, "type"=>"string", "index" => "not_analyzed" }}}],
 #   "properties"=>
 #    {"address"=>
 #      {"properties"=>
 #        {"address_line_1"=>{"type"=>"string", "index" => "not_analyzed", "fields"=>{"analyzed"=>{"type"=>"text"}}, "include_in_all"=>true, "ignore_above"=>256},
 #         "address_line_2"=>{"type"=>"string", "index" => "not_analyzed", "fields"=>{"analyzed"=>{"type"=>"text"}}, "include_in_all"=>true, "ignore_above"=>256},
 #         "city"=>
 #          {"properties"=>
 #            {"name"=>{"type"=>"string", "index" => "not_analyzed", "fields"=>{"analyzed"=>{"type"=>"text"}}, "include_in_all"=>true, "ignore_above"=>256},
 #             "state"=>
 #              {"properties"=>
 #                {"abbreviation"=>{"type"=>"string", "index" => "not_analyzed", "fields"=>{"analyzed"=>{"type"=>"text"}}, "include_in_all"=>true, "ignore_above"=>256},
 #                 "name"=>{"type"=>"string", "index" => "not_analyzed",  "fields"=>{"analyzed"=>{"type"=>"text"}}, "include_in_all"=>true, "ignore_above"=>256}}},
 #             "zip"=>{"type"=>"string", "index" => "not_analyzed", "fields"=>{"analyzed"=>{"type"=>"text"}}, "include_in_all"=>true, "ignore_above"=>256}}}}},
 #     "company"=>{"properties"=>{"name"=>{"type"=>"string", "index" => "not_analyzed", "fields"=>{"analyzed"=>{"type"=>"text"}}, "include_in_all"=>true, "ignore_above"=>256}}},
 #     "created_at"=>{"type"=>"date"},
 #     "description"=>{"type"=>"string", "index" => "not_analyzed", "fields"=>{"analyzed"=>{"type"=>"text"}}, "include_in_all"=>true, "ignore_above"=>256},
 #     "job_id"=>{"type"=>"long"},
 #     "job_type"=>{"type"=>"string", "index" => "not_analyzed", "fields"=>{"analyzed"=>{"type"=>"text"}}, "include_in_all"=>true, "ignore_above"=>256},
 #     "title"=>{"type"=>"string", "index" => "not_analyzed", "fields"=>{"analyzed"=>{"type"=>"text"}}, "include_in_all"=>true, "ignore_above"=>256},
 #     "views"=>{"type"=>"long"}}},
 # _default_:
 #  {"_all"=>{"analyzer"=>"searchkick_text_start_index"},
 #   "dynamic_templates"=>
 #    [{"string_template"=>
 #       {"match"=>"*",
 #        "match_mapping_type"=>"string",
 #        "mapping"=>{"fields"=>{"analyzed"=>{"index"=>"analyzed", "type"=>"text"}}, "ignore_above"=>256, "include_in_all"=>true, "type"=>"string", "index" => "not_analyzed" }}}]}}
  belongs_to :company_location
  has_one :address, through: :company_location
  has_one :state, through: :company_location
  has_one :company, through: :company_location
  has_one :user, through: :company_location
  has_one :feature, as: :featureable
  has_and_belongs_to_many :languages
  enum job_type: [:'full time', :'part time', :contract]
  validate :set_created_at_reformat #ToDo: how it is used
  validates :languages, presence: { message: "Please choose language"}
  validates_length_of :job_title, maximum: 26, allow_blank: false
  accepts_nested_attributes_for :company_location
  CategoryCreator = Struct.new :name, :list

  def self.set_languages(job, params) 
    keys = params.keys.select {|key| key.include? "language"}
    languages = keys.map {|key| Language.find(params[key])}
    job.languages = languages
    job
  end

  def self.featured_jobs_for_state(state_id)
    return [] if state_id.nil?
    joins = "INNER JOIN features ON (jobs.id = features.featureable_id AND features.featureable_type = 'Job') 
             INNER JOIN company_locations ON (jobs.company_location_id = company_locations.id) 
             INNER JOIN addresses ON (addresses.id = company_locations.address_id) 
             INNER JOIN cities ON (cities.id = addresses.city_id)"

    self.joins(joins)
        .where("cities.state_id = :state_id AND 
                features.created_at >= :created_at", 
                state_id: state_id, created_at: Feature::EXPIRATION_DATE)
        .order("random()")
  end

  def self.length_of_featured_jobs_for_state(state_id)
    joins = "INNER JOIN features ON (jobs.id = features.featureable_id AND features.featureable_type = 'Job') 
             INNER JOIN company_locations ON (jobs.company_location_id = company_locations.id) 
             INNER JOIN addresses ON (addresses.id = company_locations.address_id) 
             INNER JOIN cities ON (cities.id = addresses.city_id)"
    self.joins(joins)
        .where("cities.state_id = :state_id AND 
                features.created_at >= :created_at", 
                state_id: state_id, created_at: Feature::EXPIRATION_DATE)
        .length
  end

  def self.search_by_id_for_modal(id)
    job = Job.includes(:company_location => [:company, :address => [ :city => :state]])
             .where('jobs.id = ?', id)
             .first
    job.views += 1
    job.save
    return job.as_json(except: 
      [:id, :updated_at, :created_at, :created_at_reformat], 
      include: {
        company: {
          only: [:name]
        },
        address: {
          only: [:address_line_1, :address_line_2],
          include: {
            city: {
              only: [:name, :zip],
              include: {
                state: {
                  only: [:name]
                }
              }
            }
          }
        }
      }).merge({ created_at_utc: job.created_at.utc.to_s })
  end

  def self.autocomplete_what(value)
    list = Set.new
    self.search(value, {
      match: :word_start,
      load: false
    }).map do |job|
      list << job.title
      list << job.company.name
      list << job.job_type
      job[:languages][:languages].each {|l| list << l }
    end
    return list.select(&:present?).select {|x| x.upcase.include? value.upcase}
  end

  def self.autocomplete_where(value)
    list = []
    self.search(value, {
      match: :word_start,
      load: false
    }).map do |job|  
      state = job.address.city.state.name
      city = job.address.city.name
      zip = job.address.city['zip']
      state_abbrev = job.address.city.state.abbreviation

      list << state unless list.include? state
      list << city unless list.include? city
      list << zip unless list.include? zip
      list << state_abbrev unless list.include? state_abbrev
    end
    return list.compact.select {|x| x.upcase.include? value.upcase}
    # self.search(value, {
    #   match: :word_start,
    #   load: false,
    # }).map {|job| job.address.city.state.name }.uniq
  end

  def search_data
    {
      job_id: id,
      title: title,
      description: description,
      job_type: job_type,
      address: {
        address_line_1: address.address_line_1,
        address_line_2: address.address_line_2,
        city: {
          name: address.city.name,
          zip: address.city.zip,
          state: {
            name: address.city.state.name,
            abbreviation: address.city.state.abbreviation
          }
        },
      },
      company: {
        name: company.name
      },
      languages: { languages: languages.map(&:name) },
      views: views,
      created_at: created_at.to_i
    }
  end

  def self.stringify_job_ids(job_ids)
    string_ids = ""
    job_ids.each {|id| string_ids << "#{id}," }
    string_ids = string_ids.split(',').join(',')
  end

  def self.create_main_page_categories(state_id)
    cities_id = State.find(state_id).cities.pluck(:id).uniq
    sql = City.joins(:addresses => [:company_location => :jobs])
        .where(:"cities.id" => cities_id)
        .select("cities.name, COUNT(*)")
        .group("cities.name").to_sql

    result = ActiveRecord::Base.connection.execute(sql).to_a
    result_with_type = []
    result.each do |r|
      result_with_type.push(r.merge({ type: 'location' }))
    end
    location_category = CategoryCreator.new('Location', result_with_type)

    sql = Job.joins(:company_location => [:address => [:city => :state]])
       .where('states.id = ?', state_id)
      .select("jobs.job_type, COUNT(*)")
      .group("jobs.job_type")
      .to_sql

    result = ActiveRecord::Base.connection.execute(sql).to_a
    result_with_type = []
      result.each do |group|
        type_name = Job.job_types.invert[group['job_type'].to_i].split(' ').map(&:capitalize).join(' ')
        result_with_type << { 'name' => type_name, 'count' => group['count'], type: 'job_type'}
     end
    job_type_category = CategoryCreator.new('Job Type', result_with_type)
    result = nil
    [location_category, job_type_category]
  end

  def self.group_by_location(job_ids)
    sql = "SELECT \"cities\".\"name\", COUNT(*) FROM \"jobs\" INNER JOIN 
          \"company_locations\" ON \"company_locations\".\"id\" = \"jobs\".\"company_location_id\" 
          INNER JOIN \"addresses\" ON \"addresses\".\"id\" = \"company_locations\".\"address_id\" 
          INNER JOIN \"cities\" ON \"cities\".\"id\" = \"addresses\".\"city_id\" 
          WHERE \"jobs\".\"id\" IN (#{Job.stringify_job_ids(job_ids)}) 
          GROUP BY \"cities\".name"
    result = ActiveRecord::Base.connection.execute(sql).to_a
    result_with_type = []
    result.each do |r|
      result_with_type.push(r.merge({ type: 'location' }))
    end
    result = nil
    CategoryCreator.new('Location', result_with_type)
  end

  def self.group_by_company(job_ids)
    sql = "SELECT \"companies\".\"name\", COUNT(*) FROM \"jobs\" INNER JOIN 
        \"company_locations\" ON \"company_locations\".\"id\" = \"jobs\".\"company_location_id\" 
        INNER JOIN \"companies\" ON \"companies\".\"id\" = \"company_locations\".\"company_id\"

app/controllers/api/jobs_controller.rb
class Api::JobsController < ApplicationController
	before_action :set_state_name
	def index 
		respond_to do |format|
			format.html do 
        if request.xhr? 
        	@jobs = JobsSearchAdapter.new(params).search
        	set_categories(@jobs)
          render partial: 'api/jobs/jobs', layout: false, locals: { jobs: @jobs }
        else 
        	@jobs = JobsSearchAdapter.new(params).search
        	set_categories(@jobs)
        	set_search_bar_values
        end
			end
			format.json do 
				render json: JobsSearchAdapter.new(params)
			end 
		end
	end
	
	def search_by_id
		render json: Job.search_by_id_for_modal(params[:id])
	end

	def autocomplete_what
		render json: Job.autocomplete_what(params[:searchValue])		
	end

	def autocomplete_where
		render json: Job.autocomplete_where(params[:searchValue])
	end

	private
	def set_search_bar_values 
		@addressSearch = params["addressSearch"]
		@job_company_search = params["jobCompanySearch"]
	end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :require_sign_in, only: [:choose_company, :choose_company_location, :create, :new]
	#before_action :check_user_tokens, only: [:new, :create] FREE NOW 

	def index
	end

  def show 
    @job = Job.find(params[:id])
    @job.views += 1
    @job.save
    @job = Job.preload(:company_location => [:company, {:address => {:city => :state} }]).where('jobs.id = ?', params[:id]).first
  end

  def new
    @job = Job.new
    @company_location = params[:location_id]
    @languages = Language.all_for_buttons
    setup_new_job_form
  end

  def create
    @job = Job.new(job_params)
    @job = Job.set_languages(@job, params)
    @job.company_location.company.user = current_user
    if @job.save
      state = @job.state
      cookies[:location] = state.id
      cookies[:state_name] = state.name
      flash[:notice] = "Job successfully created! with id: #{@job.id} Please Refresh this page"
      redirect_to api_jobs_path(state.id, state.name)
    else      
      flash[:alert] = @job.errors.full_messages.join(', ')
      setup_new_job_form
      @company_locations = @job.company_location.user.company_locations
      @state_name = @job.state.name 
      @state_id = @job.state.id
      render :choose_company_location
    end


  #CASE 2) Only creating Job
    # @job = Job.new(job_params)

    # This is necessary because we are *not* redirect back to the
    # choose_company action. Rather, we're just *rendering* its view
    # again, but the @job instance variable is set above. The @job
    # must have a company_location populated otherwise it won't
    # produce any HTML for the nested company_location form. The
    # same applies for the address and the company, which are nested
    # under company_location.
    # Remove it when we have the company_location_id.
    # @job.company_location.build_address unless @job.company_location.address
    # @job.company_location.build_company unless @job.company_location.company

    # @job.company_location.company.user = current_user
  end
	
	def choose_state
    @new_york = State.find_ny
    @california = State.find_cali
    @illinois = State.find_il
	end
  
  def choose_company_location 
    @company_locations = CompanyLocation.find_by_user_and_state(current_user.id, params[:state_id])
    if @company_locations.blank?
      redirect_to new_jobs_path(state_name: params[:state_name], 
                                state_id: params[:state_id], 
                                location_id: :new)
    end
  end

	private	

  def job_params
    params.require(:job).permit(
      :title,
      :job_title,
      :description,
      :job_type,
      :contact_email,
      :company_location_id,
      company_location_attributes: [
        :company_id,
        company_attributes: [:name],
        address_attributes: [
          :address_line_1,
          :address_line_2,
          :city_id
        ]
      ]
    )
  end

  def setup_new_job_form
    @state = State.find(params[:state_id] || params[:job][:state_id])
    if params[:location_id] == 'new'
      @job.build_company_location   
      @job.company_location.build_company
      @job.company_location.build_address
    else
      @company_location = CompanyLocation.find(params[:location_id] || params[:job][:company_location_id])
    end
  end
end

app/views/jobs/_company_location_and_job_form.html.erb
<div class="job-form">
<%= form_for @job do |f| %> 
  <%= f.hidden_field 'state_id', value: @state.id %>
  <div class="step-1-job-form">
    <%= f.fields_for :company_location do |builder| %>
      <fieldset class="company-fieldset">
        <h2 class="orange"><%= t('Salon') %></h1>
        <!-- TODO: Allow the user to choose between creating a company or selecting an existing one -->
        <% if current_user.companies.any? %>
          <label class="select-user-companies">
          <%= t('select existing salon name') %> <br>
            <%= builder.collection_select :company_id, 
                                          current_user.companies.order("name ASC"), 
                                          :id, :name,
                                          { prompt: t('select name') }, 
                                          { class: 'user-companies-select form-control'}
                                          
                                          %>
          <br>
          
          </label>
        <% end %>
        <br>
        <div class="new-company-form-wrapper">
          <label class="input-new-company-name form-inline">
            <div class="form-group">
             <%= builder.fields_for :company do |company_builder| %>
                <%= company_builder.label :name, t('new salon name') %>
                <br>
                <%= company_builder.text_field :name, 
                                              placeholder: t('salon name'), 
                                              size: '62x1',
                                              class: 'company_name_input form-control' %>
             <% end %> 
            </div>
          </label>
        </div>
      </fieldset>

      <fieldset class="address-fieldset">
        <h2 class="orange"><%= t('address') %></h2> 
        <%= builder.fields_for :address do |address_builder| %>
          <div class="form-inline">
            <div class="form-group">
              <%= address_builder.label t('address line 1') %><br>
              <%= address_builder.text_field(
                  :address_line_1,
                  size: '62x1',
                  class: "address_line_1_input form-control",
                )
              %>
            </div> <br>
            <div class="form-group">
              <%= address_builder.label t('address line 2') %><br>
              <%= address_builder.text_field :address_line_2, size: '62x1', class: "address_line_2_input form-control" %>
            </div> <br><br>
            <div class="form-group">
              <%= address_builder.label t('city') %><br>
              <%= address_builder.collection_select(
                :city_id, 
                @state.cities.order("name ASC"), 
                :id, :name,
                { prompt: t('select city') },
                {
                  class: "city-select form-control",
                  'data-validate-required' => "Please select city",
                }
              ) %>
            </div>
          </div> <!-- form-inline -->
        <% end %> <!-- address -->
      </fieldset>
      <br>
     <button class="job-form-next-button ui right labeled icon button">
      <i class="right arrow icon"></i>
      <%= t('next') %>
    </button>
    <% end %> <!-- company_location -->
  </div> <!-- step-1-job-form -->

  <div class="step-2-job-form">
    <fieldset class="job-fieldset">
      <h1 class="orange job-header"><%= t('create job') %></h1>
      <div class="form-inline">
        <div class="form-group">
          <%= f.label t('title') %><br>
          <%= f.text_field(
              :title,
              size: '62x5',
              required: true,
              class: "form-control",
              'data-validate-required' => "Please enter job title",
            )
          %>
        </div><br>
        <div class="form-group">
          <%= f.label t('job title') %><br>
          <%= f.text_field(
              :job_title,
              size: '62x5',
              required: true,
              maxlength: 26,
              class: "form-control",
              'data-validate-required' => "Please enter job title",
            )
          %>
        </div><br>
        <div class="form-group">
          <%= f.label t('description') %><br>
          <%= f.text_area(
              :description,
              size: '62x10',
              required: true,
              class: "form-control",
              'data-validate-required' => "Please enter job description",
            )
          %>
        </div><br>
        <div class="form-group">
          <%= f.label t('contact email') %><br>
          <%= f.email_field(
              :contact_email,
              size: '62x2',
              required: true,
              class: "form-control",
              'data-validate-required' => "Please enter contact email",
            )
          %>
        </div><br>
        <div class="form-group">
          <%= f.label t('job type') %><br>
          <%= f.select :job_type, Job.job_types.keys,{}, {class: "job-type-select form-control"} %>
        </div>

        <div class="form-group post-job-which-language-question-wrapper">
          
          <div class="checkbox-container ui form">
            <div class="grouped fields">
              <h2 class="header">
                <i class="quote left icon"></i>
                <%= t('which-language-question') %>
              </h2>
              <h4 class="sub-header">
                <%= t('can-choose-more-than-one') %>
              </h4>
              <div class="checkbox-wrapper">
                <% @languages.each do |language| %>

                  <label class="custom-control custom-checkbox">
                    <input class="language-checkbox" name="language_<%= language[:id] %>" type="checkbox" class="custom-control-input big-checkbox" value="<%= language[:id] %>">
                    <span class="custom-control-indicator"></span>
                    <span class="custom-control-description">
                      <%= language[:name] %>
                    </span>
                  </label>

                  <br>
                <% end %>
              </div>
              <div class="error-box ui pointing red basic label hidden">
                Please choose a language
              </div>
          </div>
      </div>
    </fieldset>
    <br>
    <%= f.submit t('create my job'), class: "create-job-button mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
    <br>
    <br>
     <button class="job-form-back-button ui right labeled icon button">
      <i class="left arrow icon"></i>
      <%= t('back') %>
    </button>
  </div> <!-- step-2-job-form -->
  <% end %>
</div> <!-- job-form -->

app/views/jobs/_only_job_form.html.erb
<%= form_for @company_location.jobs.new, html: { class: "only-job-form"} do |f| %> 
	<%= f.hidden_field 'state_id', value: @state.id %>
  <h2><%= @company_location.company.name %></h2>
  <%= f.hidden_field :company_location_id %>

	<h1 class="orange job-header"><%= t('create job') %></h1>
	<div class="form-inline">
	  <div class="form-group">
	    <%= f.label t('title') %><br>
	    <%= f.text_field :title, size: '62x5', required: true, class: "form-control" %>
	  </div><br>
	  <div class="form-group">
	    <%= f.label t('job title') %><br>
	    <%= f.text_field :job_title, size: '62x5', required: true, maxlength: 26, class: "form-control" %>
	  </div><br>
	  <div class="form-group">
	    <%= f.label t('description') %><br>
	    <%= f.text_area :description, size: '62x10', required: true, class: "form-control" %>
	  </div><br>
	  <div class="form-group">
	    <%= f.label t('contact email') %><br>
	    <%= f.text_field :contact_email, size: '62x2', required: true, class: "form-control" %>
	  </div><br>
	  <div class="form-group">
	  <%= f.label t('job type') %><br>
	  <%= f.select :job_type, Job.job_types.keys,{}, {class: "job-type-select form-control"} %>
	  </div>
	</div>
	<br>
	<div class="form-group post-job-which-language-question-wrapper">

		<div class="checkbox-container ui form">
			<div class="grouped fields">
				<h2 class="header">
					<i class="quote left icon"></i>
					<%= t('which-language-question') %>
				</h2>
				<h4 class="sub-header">
					<%= t('can-choose-more-than-one') %>
				</h4>
				<div class="checkbox-wrapper">
					<% @languages.each do |language| %>

					<label class="custom-control custom-checkbox">
						<input class="language-checkbox" name="language_<%= language[:id] %>" type="checkbox" class="custom-control-input big-checkbox" value="<%= language[:id] %>">
						<span class="custom-control-indicator"></span>
						<span class="custom-control-description">
							<%= language[:name] %>
						</span>
					</label>

					<br>
					<% end %>
				</div>
				<div class="error-box ui pointing red basic label hidden">
					Please choose a language
				</div>
		</div>
	<br>
	<%= f.submit t('create my job'), class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
<% end %>

app/views/jobs/choose_state.html.erb
<style type="text/css">
  .state img {
    width: 100%;
    height: 250px;
  }

  h1.Heading-title {
    font-weight: bold;
    text-align: center;
    font-size: 21px;
    letter-spacing: 2px;
    margin: 3rem 0 2rem;
  }
  .state input {
    display: none;
  }
  .state img:hover {
    cursor: pointer;
    box-shadow: 0px 2px 45px 0 rgba(0,0,0,0.7);
  }
</style>

<div class="mdl-grid" id="choose-state-for-job-post">
  <header style="height: 47px; background-color: #fafafa;"></header>

  <div class="mdl-cell mdl-cell--1-col"></div>
  <div class="mdl-cell mdl-cell--10-col">
    <%= form_tag("/") do %>
      <div id="step-1">
        <h1 class="Heading-title">
          <%= t('where should we make your job post?') %>
        </h1>
        <div class="mdl-grid">
          <%= link_to choose_company_location_jobs_path(state_name: @california.name, state_id: @california.id), class: "state mdl-cell mdl-cell--4-col" do %>
            <label>
              <input type="radio" name="state" value="los-angeles">
              <img src="https://s3.us-east-2.amazonaws.com/mysalonusa/uploads/cities/california.jpg">
            </label>
          <% end %>
          <%= link_to choose_company_location_jobs_path(state_name: @new_york.name, state_id: @new_york.id), class: "state mdl-cell mdl-cell--4-col" do %>
            <label>
              <input type="radio" name="state" value="new-york">
              <img src="https://s3.us-east-2.amazonaws.com/mysalonusa/uploads/cities/newyork.jpg">
            </label>
          <% end %>
          <%= link_to choose_company_location_jobs_path(state_name: @illinois.name, state_id: @illinois.id), class: "state mdl-cell mdl-cell--4-col" do %>
            <label>
              <input type="radio" name="state" value="chicago">
              <img src="https://s3.us-east-2.amazonaws.com/mysalonusa/uploads/cities/chicago.jpg">
            </label>
          <% end %>
        </div> 
      </div> <!-- step-1 -->
    <% end %>
  </div> <!-- col-10 -->
  <div class="mdl-cell mdl-cell--1-col"></div>
</div>

app/views/jobs/new.html.erb
<div class="mdl-grid">
	<div class="mdl-cell mdl-cell--4-col">
	</div>
	<div class="mdl-cell mdl-cell--4 col mdl-cell--12-col-tablet">
		<div class="ui icon message post-job-language-notice">
      <i class="alarm outline icon"></i>
      <div class="content">
        <p><%= t("post_job_language_notice") %></p>
      </div>
    </div>
	<% if @company_location == "new" %> <!-- if user chose a company + location to create job -->
		<%= render 'company_location_and_job_form' %>
	<% else %>
	  <%= render 'only_job_form' %>
	<% end %>
	</div>
	<div class="mdl-cell mdl-cell--4-col">
	</div>
</div>