config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  ActiveAdmin.routes(self)
  root 'welcome#index'
  get '/coming_soon', to: 'welcome#coming_soon', as: 'coming_soon'

  get 'user/sign_in', to: 'sessions#sign_in', as: "sign_in"
  get "/auth/auth0/callback", to: 'sessions#callback' #lock callback
  get "/auth/failure", to: 'sessions#failure'
  post '/initial_settings', to: 'sessions#initial_settings'
  post '/change_language', to: 'sessions#change_language'
  post '/change_state', to: 'sessions#change_state'
  delete '/logout', to: 'sessions#log_out'
  
  scope module: 'api' do
    get 'api/jobs/search_by_id', to: 'jobs#search_by_id'
    get '/state/:state_id/:state_name/jobs', to: 'jobs#index', as: 'api_jobs'
    get '/api/jobs', to: 'jobs#index', as: 'api_render_jobs'
    get '/api/jobs/autocomplete/where', to: 'jobs#autocomplete_where'
    get '/api/jobs/autocomplete/what', to: 'jobs#autocomplete_what'
    get 'api/business_on_sales/suggestions', to: 'business_on_sales#suggestions'
    get 'api/business_on_sales/salons', to: 'business_on_sales#search'
    post 'api/business_on_sales', to: 'business_on_sales#create'
    get 'api/business_on_sales/cities', to: 'business_on_sales#fetch_cities'
    get 'api/business_on_sales/update_views', to: 'business_on_sales#update_view'
    get 'api/features/jobs', to: 'features#get_featured_jobs'
    get 'api/features/business_on_sales', to: 'features#get_featured_business_on_sales'
    get 'api/used_items/search', to: 'used_items#search'
    get 'api/used_items/suggestions', to: 'used_items#suggestions'
  end

  resources :jobs, only: [:show, :index, :create] do
    collection do
      get '/state/:state_name/:state_id/choose_company', to: 'jobs#choose_company_location', as: 'choose_company_location'
      get '/state/:state_name/:state_id/location/:location_id', to: 'jobs#new', as: 'new'
      
      get '/choose_state', to: 'jobs#choose_state', as: 'choose_state'
    end
  end
  
  resources :business_on_sales, only: [:new, :index]
  resources :states do
    resources :used_items, only: [:index]
  end
  resources :subscriptions, only: :create
  resources :plans, only: [:show] do 
    collection do
      get 'choose_plan', to: 'plans#display_plans', as: 'choose' #choose_plans_path
      get 'choose_business_on_sale_plan', to: 'plans#display_business_on_sale_plans', as: 'choose_business_on_sale' #choose_plans_path
    end
  end

  resources :states, only: [:index] do #state index for yellow page
  	resources :companies, path: :nail_salons, only: [:index, :show, :create] #you can only have a list by states/companies
  end 
  resources :users, only: [] do #for now
  	resources :companies, { path: :nail_salons } #ALL CRUD of companies + company_states happens under USER
  end

  scope module: 'stripe' do
    get '/checkout', to: 'subscriptions#new'
    post '/checkout_callback', to: 'subscriptions#create'
    get 'thank_you', to: 'subscriptions#thank_you', as: 'thank_you'
  end

end

app/views/partials/_advertising.html.erb
<div id="kyocharo-ad">
	<img 
		src="https://s3.us-east-2.amazonaws.com/mysalonusa/uploads/banner_cards/kyocharo_ad.jpeg"
		usemap="#Kyocharo-ad-map"
	/>
	<map name="Kyocharo-ad-map" id="Kyocharo-ad-map">
    <area alt="" title="" href="http://bds.chicagokyocharo.com/board/contentsView.php?idx=1200513" shape="rect" coords="96,85,137,120" />
    <area alt="" title="" href="http://www.nykyocharo.com/index.php" shape="rect" coords="145,85,182,120" />
    <area alt="" title="" href="http://www.kyocharoamerica.com/index.php" shape="rect" coords="190,85,230,120" />
	</map>
</div>
<!-- 
	main.css.scss / ad.js
 -->

app/views/partials/_banner_cards.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--4-col">
    <div class="demo-card-wide mdl-card post-jobs mdl-shadow--2dp">
      <div class="mdl-card__title post-jobs">
      </div>
      <div class="mdl-card__actions mdl-card--border">
        <a href="jobs/choose_state" class="fluid ui blue-button button mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
        <%= t :post_jobs %>
        </a>
      </div>
    </div>
  </div>
  <div class="mdl-cell mdl-cell--4-col">
    <div class="demo-card-wide mdl-card find-jobs mdl-shadow--2dp">
      <div class="mdl-card__title find-jobs">
      </div>
      <div class="mdl-card__actions mdl-card--border">
        <% if cookies[:location].present? && cookies[:state_name].present? %>
        <%= link_to t('find jobs'), api_jobs_path(cookies[:location], cookies[:state_name]),
             class: 'fluid ui button orange mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="mdl-cell mdl-cell--4-col mdl-cell--12-col-tablet">
    <div class="demo-card-wide mdl-card sale-business mdl-shadow--2dp">
      <div class="mdl-card__title sale-business">
      </div>
      <div class="mdl-card__actions mdl-card--border">
        <a href="/business_on_sales" class="fluid ui blue-button button mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
          <%= t :business_on_sale%>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/partials/_featured_jobs.html.erb
<style>
  .welcome-page-featured-jobs.swiper-container {
    width: 100%;
    height: auto;
    margin-left: auto;
    margin-right: auto;
  }

  .welcome-page-featured-jobs.swiper-wrapper {
  	margin-bottom: 3.5rem;
  }
  .featured-jobs.swiper-slide {
    text-align: center; 
    
    border-radius: .5em;
  }
  .featured-jobs.swiper-slide .job-title-link {
  	font-size: 1.1em;
  	text-decoration: underline;
  }

  a.job-title-link {
  	cursor: pointer; 
	}
</style>
	
	<div 
		class="ui horizontal divider"
		style="margin-bottom: 1.4em;"
	>
     <%= t('Featured Jobs') %>
  </div>

	<div class="welcome-page-featured-jobs swiper-container">
    <div class="welcome-page-featured-jobs swiper-wrapper">

    	<% @featured_jobs.each do |job| %>
	      <div class="featured-jobs swiper-slide">
	      	<div class="panel panel-info" style="margin-bottom: 0;">
					  <div class="panel-heading" style="height: 1.7em; padding: 0.4em 0; font-size: 0.9em;">
					  	<%= 
					  		truncate(
					  			"#{job.company_location.company.name}",
					  			length: 26
					  		)
					  	 %>
					  </div>
					  <div class="panel-body" style="height: 67px; padding: 10px;">
					    <a class="job-title-link" 
					       data-job-id="<%= job.id %>">
					    	<%= 
					    		truncate(
					    			pretty_print_job_title(
					    				job.job_title
					    			),
					    			length: 26
					    		) 
					    	%>	
					    </a>
					    <p>
						    <small>
						    	<%= truncate(
						    		remove_new_line_extra_white_space(job.description), 
						    		length: 44
						    	) %>
						    </small>
					    </p>
					  </div>
					</div>
	      </div>
	    <% end %>
        
    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination"></div>
    <h2 class="ui dividing header"></h2>
	</div>

app/views/partials/_flash.html.erb
<div class="ui info message flash">
	<i class="flash-message-x close icon"></i>
	<div class="header">
	<i class="alarm outline icon"></i>
	<%= flash[:notice] || flash[:alert] %>
	</div>
</div>

app/views/partials/_footer.html.erb
<footer>
			<div class="mdl-grid footer-row">
				<div class="mdl-cell mdl-cell--3-col">
					<strong><%= t('find us on facebook and twitter') %></strong>
					<ul>
						<li>
							<a href="">Facebook</a>
						</li>
						<!-- <li>
							<a href="">twitter</a>
						</li> -->
					</ul>
				</div> <!-- col-3 -->
				<div class="mdl-cell mdl-cell--3-col">
					<strong> <%= t('about us') %></strong>
					<ul>
						<li>
							<%= t('intro') %>
						</li>
					</ul>
				</div> <!-- col-3 -->
	  		<div class="mdl-cell mdl-cell--6-col">
	  			<p> 
	  				<strong>
	  					<%= t('sign up with us') %>
	  				</strong>
	  			</p>
	  			<div class="mdl-grid">
	  				<div class="mdl-cell mdl-cell--8-col">
	  					<input 
	  					id="subscribe-footer"
	  					type="email" 
	  					placeholder="<%= t :'your email' %>">
	  				</div>
	  				<div class="mdl-cell mdl-cell--4-col">
	  					<input class="subscribe-button button-primary" type="submit" name="" value='<%= t :submit %>'>
	  				</div>
	  			</div>
	  		</div> <!-- col-9 -->
			</div>	
		</footer>

app/views/partials/_jobs_search_bar.html.erb
<%= form_tag(
      api_render_jobs_path,
      method: :get,
      class: "jobs-search-bar-container mdl-grid",
      style: "padding-left: 0;",
      id: "search-form",
      remote: controller_name != "welcome",
    ) do
%>
	<div class="keyword-search mdl-cell mdl-cell--6-col" style="margin-left: 0;">
    <strong>
      <span id='what' class="orange">
        <%= t :what %>
      </span>
    </strong>
		<div class="ui fluid icon input">
      <input
        class="job-company-search"
        name="jobCompanySearch"
        type="text"
        placeholder="<%= [t('job title'), t('keywords'), t('company')].to_sentence(last_word_connector: " or ") %>"
        value="<%= @job_company_search %>"
      >
		</div>
	</div>
	<div class="job-search mdl-cell mdl-cell--6-col" style="margin-left: 0;">
    <strong>
      <span id='where' class="orange">
        <%= t :where %>
      </span>
    </strong>
		<div class="ui fluid action input">
      <input
        class="address-search"
        type="text"
        name="addressSearch"
        placeholder="<%= [t('city'), t('state'), t('zipcode')].to_sentence(last_word_connector: " or ") %>"
        value="<%= @addressSearch %>"
      >
      <button class="<%= controller_name == 'welcome' ? 'welcome-job-search-button' : 'job-search-button' %> job-search-button ui button">
        <%= t(:search).capitalize %>
      </button>
		</div>
	</div>
  <div class="job-search-bar-notification">
  <%#= t("please search in english") %>
  </div>
  <div class="job-search-bar-notification">
  <%#= t("all user posts are in english") %>
  </div>
<% end %>

app/views/partials/_jobs_side_menu.html.erb
<div class="<%= params[:controller].split('/').join('_') %> jobs-side-menu ui link list">
	<% categories.each do |category| %>
		<div class="item">
			<div class="header">
				<%= t category.name.downcase.to_sym %>
			</div>
			<div class="category-wrapper">
				<% category.list.each do |category| %>
					<a class="category-item" href="#">
						<div class="item" style="color: rgba(0,0,0,0.7)">
							&nbsp;
							<span class="item-name">
							<%= category['name'] %>
							 </span>
							(<%= category['count'] %>)
						</div>
					</a>
				<% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/partials/_main_page_jobs.html.erb
<div class="main-page-jobs-search">
  <div class="mdl-grid jobs-top-header">
    <div class="filters mdl-cell mdl-cell--3-col">
    </div>
    <div class="jobs-container mdl-cell mdl-cell--9-col">
      <!-- job search form -->

      <%= render "partials/jobs_search_bar" %>

      <div class="jobs-header-container">
        <h1 id="job_list_state_name_header" class="ui header orange" style="margin-top: 1rem;">
          <%= pretty_print_state @state_name %>
        </h1>
      </div>
    </div>
  </div>
</div>

<div class="main-jobs-container mdl-grid">
  <div class="filters mdl-cell mdl-cell--3-col">
    <% if @categories %>
      <%= render 'partials/jobs_side_menu', categories: @categories %> 
    <% end %>
  </div>
  <div class="jobs-container mdl-cell mdl-cell--9-col">
    <div id="jobs-list-wrapper">
      <div class="jobs ui divided items">
        <% jobs.each do |job| %>
          <div class="job item">
            <div class="content">
              <a class="header" style="color: #3f51b5;">
                <a class="job-title-link" data-job-id="<%= job.id %>">
                  <%= truncate(job.title.capitalize, length: 55) %>
                </a>
              </a>
              <div class="ui left pointing label teal" style="float: right; ">
                <%= job.views.to_i %> <%= t :views %>
              </div><br>
              <span stlye="display: inline;">
                <%= job.company_location.company.name %>
                <div class="meta" style="display: inline;">	
                  <span class="city_name">- <%= job.company_location.address.city.name %></span>
                </div>	
              </span>						
              <div class="welcome-description" style="margin: 0;">
                <%= truncate(job.description, length: 70) %>
              </div>
              <div class="extra" style="margin-top: 0; ">
                <div class="ui label pink">
                  <span lang="<%= I18n.locale = :en %>">
                    <%= time_ago_in_words job.created_at %> 
                    <%= t :ago %>
                  </span>
                  <span lang="<%= I18n.locale = cookies[:locale] %>">
                  </span>
                </div>

                <% if job.languages.present? %>
                  <% job.languages.each do |lang| %>
                    <div class="ui label blue">
                      <%= lang.name %> speaker
                    </div>
                  <% end %>
                <% else %>
                  <div class="ui label"><%= job.job_type %></div>                
                  <div class="ui label">
                    <%= job.company_location.address.city.name %>
                  </div>
                <% end %>
                
              </div>
            </div> <!-- content -->
          </div> <!-- item -->
        <% end %>
      </div> <!-- ui divided items -->
    </div> <!-- jobs-wrapper -->
    <br>
    <br>
    <a href="<%= "state/#{cookies[:location]}/#{cookies[:state_name]}/jobs" %>">
      <button class="blue fluid ui button more-jobs-button">
        <%= t :view_more_jobs %>
      </button>  </div> 
    </a>

</div>

app/views/partials/_welcome_business_on_sale.html.erb
<div id="welcome-page-business-on-sale-top-container" class="mdl-grid">
  <div class="mdl-cell mdl-cell--12-col">
    <h3><%= t :business_on_sale %></h3>
  </div> <!-- col-12 -->
  
  <%= link_to business_on_sales_path do %>
    <div id="welcome-page-business-on-sale-banner" class="col-xs-12">
      <img src="https://s3.us-east-2.amazonaws.com/mysalonusa/uploads/banners/BUTTOM_BANNER_1.jpg" 
      />
    </div>
  <% end %>

  <div class="mdl-cell mdl-cell--12-col">
    <div class="mdl-grid">
      
    <div class="mdl-cell mdl-cell--12-col">
      <!-- Swiper -->
      <div class="business-sale-swiper-container swiper-container">
        <div class="swiper-wrapper">
          <div class="swiper-slide">
            <img src="https://mysalonusa.s3.amazonaws.com/uploads/business_on_sale/images/61/329-22.jpg">
            <div class="details">
              <div>
                <h4 class="ui header">
                  Heather's Nail Salon
                </h4>
                <a class="ui blue label">
                  <%= number_to_currency('50000') %>
                </a>
              </div>
            </div>
          </div>
          <div class="swiper-slide">
            <img src="https://mysalonusa.s3.amazonaws.com/uploads/business_on_sale/images/83/5.jpg">
            <div class="details">
              <div>
                <h4 class="ui header">
                  Glamcode Beauty Bar
                </h4>
                <a class="ui blue label">
                  <%= number_to_currency('80000') %>
                </a>
              </div>
            </div>
          </div>
          <div class="swiper-slide">
            <img src="https://s3.us-east-2.amazonaws.com/mysalonusa/uploads/business_on_sale/images/22/tt3.jpg">
            <div class="details">
              <div>
                <h4 class="ui header">
                  Tanning Salon - quick sale!!
                </h4>
                <a class="ui blue label">
                  <%= number_to_currency('85000') %>
                </a>
              </div>
            </div>
          </div>
          <div class="swiper-slide">
            <img src="https://s3.us-east-2.amazonaws.com/mysalonusa/uploads/business_on_sale/images/21/ch2.jpg">
            <div class="details">
              <div>
                <h4 class="ui header">
                  Hair Salon For Sale
                </h4>
                <a class="ui blue label">
                  Contact For Price
                </a>
              </div>
            </div>
          </div>
          <div class="swiper-slide">
            <img src="https://s3.us-east-2.amazonaws.com/mysalonusa/uploads/business_on_sale/images/19/g1.jpg">
            <div class="details">
              <div>
                <h4 class="ui header">
                  Glendale Salon
                </h4>
                <a class="ui blue label">
                  <%= number_to_currency('31990') %>
                </a>
              </div>
            </div>
          </div>
          <div class="swiper-slide">
            <img src="https://mysalonusa.s3.amazonaws.com/uploads/business_on_sale/images/60/329-1.jpg">
            <div class="details">
              <div>
                <h4 class="ui header">
                  Roberto's Hair Studio
                </h4>
                <a class="ui blue label">
                  <%= number_to_currency('19500') %>
                </a>
              </div>
            </div>
          </div>
          <div class="swiper-slide">
            <img src="https://mysalonusa.s3.amazonaws.com/uploads/business_on_sale/images/74/8.jpg">
            <div class="details">
              <div>
                <h4 class="ui header">
                  Expert Hair Design By Lek
                </h4>
                <a class="ui blue label">
                  <%= number_to_currency('31000') %>
                </a>
              </div>
            </div>
          </div>
          <div class="swiper-slide">
            <img src="https://mysalonusa.s3.amazonaws.com/uploads/business_on_sale/images/67/11.jpg">
            <div class="details">
              <div>
                <h4 class="ui header">
                  Salón De Belleza Beauty Salon
                </h4>
                <a class="ui blue label">
                  <%= number_to_currency('15000') %>
                </a>
              </div>
            </div>
          </div>
          <div class="swiper-slide">
            <img src="https://mysalonusa.s3.amazonaws.com/uploads/business_on_sale/images/40/326-51.jpg">
            <div class="details">
              <div>
                <h4 class="ui header">
                  Nail salon relocation for sale
                </h4>
                <a class="ui blue label">
                 Contact For Price
                </a>
              </div>
            </div>
          </div>
          <div class="swiper-slide">
            <img src="https://mysalonusa.s3.amazonaws.com/uploads/business_on_sale/images/35/326-21.jpg">
            <div class="details">
              <div>
                <h4 class="ui header">
                  Established beauty salon
                </h4>
                <a class="ui blue label">
                 <%= number_to_currency('32000') %>
                </a>
              </div>
            </div>
          </div>
          <div class="swiper-slide">
            <img src="https://mysalonusa.s3.amazonaws.com/uploads/business_on_sale/images/43/327-31.jpg">
            <div class="details">
              <div>
                <h4 class="ui header">
                  Nail Salon with Hair Stylist
                </h4>
                <a class="ui blue label">
                  <%= number_to_currency('59000') %>
                </a>
              </div>
            </div>
          </div>
          <div class="swiper-slide">
            <img src="https://mysalonusa.s3.amazonaws.com/uploads/business_on_sale/images/41/327-14.jpg">
            <div class="details">
              <div>
                <h4 class="ui header">
                  Tanning salon for sale
                </h4>
                <a class="ui blue label">
                  <%= number_to_currency('85000') %>
                </a>
              </div>
            </div>
          </div>
          <div class="swiper-slide">
            <img src="https://mysalonusa.s3.amazonaws.com/uploads/business_on_sale/images/28/325-3.jpg">
             <div class="details">
              <div>
                <h4 class="ui header">
                  Versailles Salon
                </h4>
                <a class="ui blue label">
                  <%= number_to_currency('15000') %>
                </a>
              </div>
            </div>
          </div>
          <div class="swiper-slide">
            <img src="https://mysalonusa.s3.amazonaws.com/uploads/business_on_sale/images/14/vannuys3.jpg">
            <div class="details">
              <div>
                <h4 class="ui header">
                  Beauty salon for sale (van nuys)
                </h4>
                <a class="ui blue label">
                  <%= number_to_currency('27000') %>
                </a>
              </div>
            </div>
          </div>
        <!-- Add Pagination -->
      </div> <!-- swiper container -->
    </div> <!-- col-10 -->
  </div> <!-- mdl-grid -->
</div> <!-- 12 col -->
</div> <!-- mdl-grid -->

<div class="pagination-wrapper">
  <div class="business-sale-swiper-pagination"></div>
</div>