config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  ActiveAdmin.routes(self)
  root 'welcome#index'
  get '/coming_soon', to: 'welcome#coming_soon', as: 'coming_soon'

  get 'user/sign_in', to: 'sessions#sign_in', as: "sign_in"
  get "/auth/auth0/callback", to: 'sessions#callback' #lock callback
  get "/auth/failure", to: 'sessions#failure'
  post '/initial_settings', to: 'sessions#initial_settings'
  post '/change_language', to: 'sessions#change_language'
  post '/change_state', to: 'sessions#change_state'
  delete '/logout', to: 'sessions#log_out'
  
  scope module: 'api' do
    get 'api/jobs/search_by_id', to: 'jobs#search_by_id'
    get '/state/:state_id/:state_name/jobs', to: 'jobs#index', as: 'api_jobs'
    get '/api/jobs', to: 'jobs#index', as: 'api_render_jobs'
    get '/api/jobs/autocomplete/where', to: 'jobs#autocomplete_where'
    get '/api/jobs/autocomplete/what', to: 'jobs#autocomplete_what'
    get 'api/business_on_sales/suggestions', to: 'business_on_sales#suggestions'
    get 'api/business_on_sales/salons', to: 'business_on_sales#search'
    post 'api/business_on_sales', to: 'business_on_sales#create'
    get 'api/business_on_sales/cities', to: 'business_on_sales#fetch_cities'
    get 'api/business_on_sales/update_views', to: 'business_on_sales#update_view'
    get 'api/features/jobs', to: 'features#get_featured_jobs'
    get 'api/features/business_on_sales', to: 'features#get_featured_business_on_sales'
    get 'api/used_items/search', to: 'used_items#search'
    get 'api/used_items/suggestions', to: 'used_items#suggestions'
  end

  resources :jobs, only: [:show, :index, :create] do
    collection do
      get '/state/:state_name/:state_id/choose_company', to: 'jobs#choose_company_location', as: 'choose_company_location'
      get '/state/:state_name/:state_id/location/:location_id', to: 'jobs#new', as: 'new'
      
      get '/choose_state', to: 'jobs#choose_state', as: 'choose_state'
    end
  end
  
  resources :business_on_sales, only: [:new, :index]
  resources :states do
    resources :used_items, only: [:index]
  end
  resources :subscriptions, only: :create
  resources :plans, only: [:show] do 
    collection do
      get 'choose_plan', to: 'plans#display_plans', as: 'choose' #choose_plans_path
      get 'choose_business_on_sale_plan', to: 'plans#display_business_on_sale_plans', as: 'choose_business_on_sale' #choose_plans_path
    end
  end

  resources :states, only: [:index] do #state index for yellow page
  	resources :companies, path: :nail_salons, only: [:index, :show, :create] #you can only have a list by states/companies
  end 
  resources :users, only: [] do #for now
  	resources :companies, { path: :nail_salons } #ALL CRUD of companies + company_states happens under USER
  end

  scope module: 'stripe' do
    get '/checkout', to: 'subscriptions#new'
    post '/checkout_callback', to: 'subscriptions#create'
    get 'thank_you', to: 'subscriptions#thank_you', as: 'thank_you'
  end

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  monetize :price_cents
	enum name: { Standard: 0, Gold: 1, Platinum: 2}
	validates :name, presence: true
	validates :name, uniqueness: { case_sensitive: false } 
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
	before_action :require_sign_in, only: [:display_plans, :display_business_on_sale_plans]

	def display_plans  #for jobs
		#NOTICE: Always expecting session[:intended_url]
		redirect_to root_path if session[:intended_url].blank?
		@plans = Plan.all
	end

	def display_business_on_sale_plans
		redirect_to root_path if session[:intended_url].blank?
		@business_on_sale_plans = BusinessOnSalePlan.all
	end
end

app/views/plans/display_business_on_sale_plans.html.erb
<div class="choose-business-on-sale-plan-container">
  <div class="title">
    <h1><%= t('token intro') %></h1>
  </div>
  <header>
    <div id="fdw-pricing-table" class="mdl-grid">
      <div class="plan-wrapper business-on-sale">
        <% @business_on_sale_plans.each_with_index do |plan, i| %>
          <div id="business-on-sale-plan-box"class="plan plan<%= "#{i + 1}" %>">
            <%= form_tag(checkout_callback_path, class: "plan-form") do %>
              <%= hidden_field_tag "price_cents", plan.price_cents %>
              <%= hidden_field_tag "stripe_token", '' %>
              <%= hidden_field_tag "type", 'business_on_sale' %>
              <label for="<%= "plan_#{plan.id}"%>">
                <div class="header">
                  <%= t(plan.name.downcase) %>
                </div>
                <div class="price"><%= plan.price.format %></div>
  <!--               <div class="monthly">one time pay</div> -->
                <ul style="word-wrap: break-word;">
                  <li><%= pluralize(plan.total_tokens, 'post') %></li>
                  <li>
                    <b>
                      <% if plan.name.downcase == 'single pay' %>
                        <%= t('single pay description') %>
                      <% elsif plan.name.downcase == 'group package' %>
                        <%= t('group package description') %>
                      <% end %>
                    </b>
                  </li>
                </ul>
                <%= submit_tag('pay', class: "stripe-button-el signup") %>
                <input class="plan-radio hidden" checked="checked" type="radio" name="plan_id" id="<%= "plan_#{plan.id}" %>" value="<%= "#{plan.id}" %>">
              </label>
            <% end %> 
          </div>
        <% end %>
      </div>
    </div>
  </header>
</div>

app/views/plans/display_plans.html.erb
<!-- plans for jobs -->
<div class="choose-plan-container">
  <div class="title">
    <h1><%= t('token intro') %></h1>
  </div>
  <header>
    <div id="fdw-pricing-table" class="mdl-grid">
      <div class="job-plan-wrapper">
        <% @plans.each_with_index do |plan, i| %>
          <div id="job-plan-box" class="plan plan<%= "#{i + 1}" %> mdl-cell mdl-cell--4-col">
            <%= form_tag(checkout_callback_path, class: "plan-form") do %>
              <%= hidden_field_tag "price_cents", plan.price_cents %>
              <%= hidden_field_tag "stripe_token", '' %>
              <%= hidden_field_tag "type", 'job' %>
              <label for="<%= "plan_#{plan.id}"%>">
                <div class="header"><%= t(plan.name) %></div>
                <% if plan.name == 'Standard' %>
                  <div class="price"><%= plan.price.format %></div>
                  <div class="monthly"><%= t('one time pay') %></div>
                  <ul style="word-wrap: break-word;">
                    <li><%= t('one post') %></li>
                    <li><b><%= t('you can upload one post on our website') %></b></li>
                  </ul>
                <% elsif plan.name == 'Gold' %>
                  <div class="price"><%= plan.price.format %></div>
                  <div class="monthly"><%= t('one time pay') %></div>
                  <ul style="word-wrap: break-word;">
                    <li><%= t('five posts') %></li>
                    <li><b><%= t('you can upload 5 posts on our website anytime') %></b></li>
                  </ul>
                <% elsif plan.name == 'Platinum' %>
                  <div class="price"><%= plan.price.format %></div>
                  <div class="monthly"><%= t('one time pay') %></div>
                  <ul style="word-wrap: break-word;">
                    <li><%= t('ten posts') %></li>
                    <li><b><%= t('you can upload 10 posts on our website anytime') %></b></li>
                  </ul>
                <% end %>
                
                <%= submit_tag('pay', class: "stripe-button-el signup") %>
                <input class="plan-radio hidden" checked="checked" type="radio" name="plan_id" id="<%= "plan_#{plan.id}" %>" value="<%= "#{plan.id}" %>">
              </label>
            <% end %> 
          </div>
        <% end %>
      </div>
    </div>
  </header>
</div>