config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  ActiveAdmin.routes(self)
  root 'welcome#index'
  get '/coming_soon', to: 'welcome#coming_soon', as: 'coming_soon'

  get 'user/sign_in', to: 'sessions#sign_in', as: "sign_in"
  get "/auth/auth0/callback", to: 'sessions#callback' #lock callback
  get "/auth/failure", to: 'sessions#failure'
  post '/initial_settings', to: 'sessions#initial_settings'
  post '/change_language', to: 'sessions#change_language'
  post '/change_state', to: 'sessions#change_state'
  delete '/logout', to: 'sessions#log_out'
  
  scope module: 'api' do
    get 'api/jobs/search_by_id', to: 'jobs#search_by_id'
    get '/state/:state_id/:state_name/jobs', to: 'jobs#index', as: 'api_jobs'
    get '/api/jobs', to: 'jobs#index', as: 'api_render_jobs'
    get '/api/jobs/autocomplete/where', to: 'jobs#autocomplete_where'
    get '/api/jobs/autocomplete/what', to: 'jobs#autocomplete_what'
    get 'api/business_on_sales/suggestions', to: 'business_on_sales#suggestions'
    get 'api/business_on_sales/salons', to: 'business_on_sales#search'
    post 'api/business_on_sales', to: 'business_on_sales#create'
    get 'api/business_on_sales/cities', to: 'business_on_sales#fetch_cities'
    get 'api/business_on_sales/update_views', to: 'business_on_sales#update_view'
    get 'api/features/jobs', to: 'features#get_featured_jobs'
    get 'api/features/business_on_sales', to: 'features#get_featured_business_on_sales'
    get 'api/used_items/search', to: 'used_items#search'
    get 'api/used_items/suggestions', to: 'used_items#suggestions'
  end

  resources :jobs, only: [:show, :index, :create] do
    collection do
      get '/state/:state_name/:state_id/choose_company', to: 'jobs#choose_company_location', as: 'choose_company_location'
      get '/state/:state_name/:state_id/location/:location_id', to: 'jobs#new', as: 'new'
      
      get '/choose_state', to: 'jobs#choose_state', as: 'choose_state'
    end
  end
  
  resources :business_on_sales, only: [:new, :index]
  resources :states do
    resources :used_items, only: [:index]
  end
  resources :subscriptions, only: :create
  resources :plans, only: [:show] do 
    collection do
      get 'choose_plan', to: 'plans#display_plans', as: 'choose' #choose_plans_path
      get 'choose_business_on_sale_plan', to: 'plans#display_business_on_sale_plans', as: 'choose_business_on_sale' #choose_plans_path
    end
  end

  resources :states, only: [:index] do #state index for yellow page
  	resources :companies, path: :nail_salons, only: [:index, :show, :create] #you can only have a list by states/companies
  end 
  resources :users, only: [] do #for now
  	resources :companies, { path: :nail_salons } #ALL CRUD of companies + company_states happens under USER
  end

  scope module: 'stripe' do
    get '/checkout', to: 'subscriptions#new'
    post '/checkout_callback', to: 'subscriptions#create'
    get 'thank_you', to: 'subscriptions#thank_you', as: 'thank_you'
  end

end

app/views/layouts/_choose_language_choose_state_modal.erb
<div class="choose-language-modal modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class="modal-title">Change Language</h2>
      </div>
      <div class="modal-body">
        <div id="choose-language-modal">
					<%= form_tag("/change_language") do %>
						<div>
				      <div class="">
					      <div class="language-col col-xs-12 col-sm-offset-1 col-sm-5">
						      <label class="language mdl-js-button">
						        <input name="locale" type="radio" value="en">
						        <img src="https://s3.us-east-2.amazonaws.com/mysalonusa/uploads/flags/usaflag.jpg"
						        />
						        English
						      </label>
					      </div>
					      <div class="language-col col-xs-12 col-sm-5">
						      <label class="language">
						        <input name="locale" type="radio" value="ko">
						        <img src="https://s3.us-east-2.amazonaws.com/mysalonusa/uploads/flags/koreanflag.jpg"
						        />
						        Korean
						      </label>
					      </div>
					    </div>

					    <div class="">
					      <div class="language-col col-xs-12 col-sm-offset-1 col-sm-5">
						      <label class="language">
						        <input name="locale" type="radio" value="mo">
						        <img src="https://s3.us-east-2.amazonaws.com/mysalonusa/uploads/flags/Mongolia_Large_Flag.png"
						        />
						        Mongolian
						      </label>
						    </div>
						    <div class="language-col col-xs-12 col-sm-5">
						      <label class="language">
						        <input name="locale" type="radio" value="vi">
						        <img src="https://s3.us-east-2.amazonaws.com/mysalonusa/uploads/flags/vietnam_flag.gif"
						        />
						        Vietnamese
						      </label>
						    </div>
						  </div>
						  
						</div>
					<% end %>
				</div> <!-- choose-language-modal -->

      </div> <!--modal-body -->
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<div class="choose-state-modal modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class="modal-title">Change State</h2>
      </div>
      <div class="modal-body">
        <div id="choose-state-modal">
					<%= form_tag("/change_state") do %>
						<div>
				      <br>
					      <div class="state-col col-xs-12 col-sm-4">
						      <label class="state">
						        <input name="location" type="radio" value="california">
						        <img src="https://s3.us-east-2.amazonaws.com/mysalonusa/uploads/cities/california.jpg"
						        />
						      </label>
					      </div>
					      <div class="state-col col-xs-12 col-sm-4">
						      <label class="state mdl-js-button">
						        <input name="location" type="radio" value="new york">
						        <img src="https://s3.us-east-2.amazonaws.com/mysalonusa/uploads/cities/newyork.jpg"
						        />
						      </label>
					      </div>
					      <div class="state-col col-xs-12 col-sm-4">
						      <label class="state">
						        <input name="location" type="radio" value="illinois">
						        <img src="https://s3.us-east-2.amazonaws.com/mysalonusa/uploads/cities/chicago.jpg"
						        />
						      </label>
						    </div>
						</div>
					<% end %>
				</div> <!-- choose-state-modal -->
      </div> <!--modal-body -->
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/layouts/_ie_detected_modal.html.erb
<div class="ie-detected modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Sorry!</h4>
      </div>
      <div class="modal-body">
          <div class="alert alert-success">
            <strong>You are using Internet Explorer</strong><br>
            To use our service, please consider using below browsers.
          </div>

          <div class="col-xs-4">
            <a href="https://www.google.com/chrome/browser/desktop/index.html?brand=CHBD&gclid=Cj0KEQjwuOHHBRDmvsHs8PukyIQBEiQAlEMW0M00nTFJA2ZfznvxdyAK18OTGhp72EFwXZv9re0Vw04aApvV8P8HAQ&dclid=CPCIxYves9MCFVM4Twod6BgIag"
              style="cursor: pointer;">
              <img src="https://s3.us-east-2.amazonaws.com/mysalonusa/uploads/browser-images/chrome.jpeg" 
              />
            </a>
          </div>
           <div class="col-xs-4">
            <a href="https://www.mozilla.org/en-US/firefox/new/" style="cursor: pointer;">
              <img 
                src="https://s3.us-east-2.amazonaws.com/mysalonusa/uploads/browser-images/firefox.jpeg" 
              />
            </a>
          </div>
           <div class="col-xs-4">
            <a href="https://www.apple.com/safari/" style="cursor:pointer;">
              <img src="https://s3.us-east-2.amazonaws.com/mysalonusa/uploads/browser-images/safari.jpeg" 
              />
            </a>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Okay</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/layouts/_initial_settings_modal.html.erb
<div class="initial-settings-modal modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="ui header" style="text-align: center; font-size: 1.5rem;font-weight: 100;"> 
          Welcome to MySalon <span style="font-size: 1.4rem; color: #f2711c;">USA</span>
        </h2>
      </div>
      <div class="modal-body">
        <div id="initial-settings">
          <%= form_tag "/initial_settings" do %>
              <div id="step-1">
                <h2 style="font-size: 2rem;">Choose Your Location</h2>
                <br>
                <div class="mdl-grid">
                  <div class="mdl-cell mdl-cell--4-col">
                    <label> 
                      <input name="location" type="radio" value="california">
                      <img src="https://s3.us-east-2.amazonaws.com/mysalonusa/uploads/cities/california.jpg" />
                    </label>
                  </div>
                  <div class="mdl-cell mdl-cell--4-col">
                    <label> 
                      <input name="location" type="radio" value="new york">
                      <img src="https://s3.us-east-2.amazonaws.com/mysalonusa/uploads/cities/newyork.jpg" />
                    </label>
                  </div>
                   <div class="mdl-cell mdl-cell--4-col">
                    <label> 
                      <input name="location" type="radio" value="illinois">
                      <img src="https://s3.us-east-2.amazonaws.com/mysalonusa/uploads/cities/chicago.jpg" />
                    </label>
                  </div>
                </div>
              </div> <!-- step-1 -->

              <div id="step-2">
                <!-- <h2 class="ui header" style="font-size: 1.4rem;font-weight: 100;"> 
                  We connect local communities <span style="font-size: 1.4rem; color: #f2711c;">together.</span>
                </h2> -->
                <h2 class="ui header" style="font-size: 2rem;font-weight: 100;"> 
                  <span style="font-size: 2rem; color: #f2711c;">One</span> Community.
                </h2>
                <a id="back" class="mdl-button mdl-js-button mdl-button--primary" style="margin: .5em;">&lt; Back</a>
                <h2 style="margin: 0.5em;">Choose Your Language</h2>
                <br>
                <div class="row">
                  <div class="col-xs-12 col-sm-offset-2 col-sm-4"> 
                    <label class="language mdl-js-button">
                      <input name="locale" type="radio" value="en">
                      <img src="https://s3.us-east-2.amazonaws.com/mysalonusa/uploads/flags/usaflag.jpg"
                      />
                      English
                    </label>
                  </div>

                  <div class="col-xs-12 col-sm-4"> 
                    <label class="language">
                      <input name="locale" type="radio" value="ko">
                      <img src="https://s3.us-east-2.amazonaws.com/mysalonusa/uploads/flags/koreanflag.jpg"
                      />
                      Korean
                    </label>
                  </div>
                </div> <!-- row -->

                <div class="row">
                  <div class="col-xs-12 col-sm-offset-2 col-sm-4">
                    <label class="language">
                      <input name="locale" type="radio" value="mo">
                      <img src="https://s3.us-east-2.amazonaws.com/mysalonusa/uploads/flags/Mongolia_Large_Flag.png"
                      />
                      Mongolian
                    </label>
                  </div>

                  <div class="col-xs-12 col-sm-4"> 
                    <label class="language">
                      <input name="locale" type="radio" value="vi">
                      <img src="https://s3.us-east-2.amazonaws.com/mysalonusa/uploads/flags/vietnam_flag.gif"
                      />
                      Vietnamese
                    </label>
                  </div>
                </div> <!-- row -->
              </div>
          <% end %>
        </div> <!--initial-settings -->

      </div><!-- modal-body -->
      
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Job Search | Salon Jobs. Your Area. | MySalon USA</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 <script src="https://cdn.auth0.com/js/lock/10.7.3/lock.min.js"></script>
 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
  <link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet"> 
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
  <script src="https://checkout.stripe.com/checkout.js"></script>
</head>
<body class="<%= "#{controller_name}-#{action_name}" %>">
<% if flash[:notice] || flash[:alert] %>
<%= render 'partials/flash' %>
<% end %>

<div class="mdl-layout--no-desktop-drawer-button mdl-layout mdl-js-layout mdl-layout--fixed-header">
  <header class="mdl-layout__header ">
    <div class="mdl-layout__header-row">
      <span class="mdl-layout-title">
      <%= link_to ' MySalon', "/", class: 'logo'  %>
      </span>
      <!-- Add spacer, to align navigation to the right -->
      <div class="mdl-layout-spacer">
        <span id="usa">USA </span>
        <span class="logo_state_name" style="margin-left: 1rem;">        
          <% if cookies[:state_name].present? %>
            <%= t pretty_print_state("#{cookies.try(:[], :state_name)}").downcase %>
          <% end %>
        </span>
      </div>
      <!-- Navigation. We hide it in small screens. -->
      <nav class="mdl-navigation mdl-layout--large-screen-only mdl-layout--no-drawer-button ">
        <% if current_user %>
        <!-- FREE at the moment -->
          <!-- <a class="mdl-navigation__link">
            <span class="ui orange"> 
              <%= current_user.tokens_left %> <%= t 'tokens left' %>
            </span>
          </a>
          <a class="mdl-navigation__link">
            <span class="ui orange"> 
              <%= current_user.business_on_sale_tokens_left %> <%= t 'business on sale left' %>
            </span>
          </a> -->
        <% end %>

        <a class="mdl-navigation__link change_state_link" href="#">
          <%= t 'change state'%>
        </a>
        <a class="mdl-navigation__link change_language_link" href="#">
          <%= t 'change language'%>
        </a>

        <% if current_user %>
          <%= link_to t('sign out'), logout_path, method: :delete, class: 'mdl-navigation__link' %>
        <% else %>
          <%= link_to t('sign in'), sign_in_path, id: 'sign-in', class: 'mdl-navigation__link' %>
        <% end %>
      </nav>
    </div>
  </header>
  <div class="mdl-layout__drawer"> <!-- cell -->
    <nav class="mdl-navigation">
      <% if current_user %>
        <!-- FREE at the moment --> 
        <!-- <a class="mdl-navigation__link">
          <span class="ui orange"> 
            <%= current_user.tokens_left %> <%= t 'tokens left' %>
          </span>
        </a>
        <a class="mdl-navigation__link">
          <span class="ui orange"> 
            <%= current_user.business_on_sale_tokens_left %> <%= t 'business on sale left' %>
          </span>
        </a> -->
      <% end %>
      <%= link_to t(:post_jobs), choose_state_jobs_path, class: "mdl-navigation__link" %>
      <a class="mdl-navigation__link" href="/business_on_sales/new">
        <%= t 'sale/post my business' %>
      </a>
      <% if cookies[:location].present? && cookies[:state_name].present? %>
        <%= link_to t('find jobs'), api_jobs_path(cookies[:location], cookies[:state_name]), class: "mdl-navigation__link" %>
      <% end %>
      <a class="mdl-navigation__link" href="/business_on_sales">
        <%= t 'business on sale' %>
      </a>
      <a class="mdl-navigation__link change_state_link" href="#">
        <%= t 'change state'%>
      </a>
      <a class="mdl-navigation__link change_language_link" href="#">
        <%= t 'change language'%>
      </a>

      <% if current_user %>
        <%= link_to t('sign out'), logout_path, method: :delete, class: 'mdl-navigation__link' %>
      <% else %>
        <%= link_to t('sign in'), sign_in_path, id: 'sign-in-2', class: 'mdl-navigation__link' %>
      <% end %>
    </nav>
  </div>

  <%= react_component("NavApp", props: @nav_menu_app_props.merge({
    language: { 
      menu: t('menu'),
      click_on: t('click to open'),
      click_off: t('click to close'),
      home: t('home'),
      tokens_left: t('tokens left'),
      business_post_left: t('business on sale left'),
      search_jobs: t('search jobs'),
      search_business_on_sale: t('search business on sale'),
      sale_or_post_my_business: t('sale/post my business'),
      post_jobs: t('post_jobs')
    }
  }), prerender: false) %>


  <main class="mdl-layout__content">
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header remodal-bg">
      <main class="mdl-layout__content"> 
        <%= yield %>
        <% if controller_name == 'welcome' %>
          <%= render 'partials/footer' %>
        <% end %>
      </main>
    </div>
  </main>
</div>

<div class="modal fade" id="used-item-modal">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Modal body text goes here.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary">Save changes</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

 <%= render partial: "layouts/initial_settings_modal" %>
 <%= render partial: "layouts/choose_language_choose_state_modal" %>
 <%= render partial: "layouts/ie_detected_modal" %>
  <script>
    window.intercomSettings = {
      app_id: "tqk65xzz"
    };
  </script>
  <script>(function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://widget.intercom.io/widget/tqk65xzz';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);}if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})()</script>

  <% if Rails.env.production? %>
    <a title="Google Analytics Alternative" href="http://clicky.com/101042100"><img alt="Google Analytics Alternative" src="//static.getclicky.com/media/links/badge.gif" border="0" /></a>
    <script src="//static.getclicky.com/js" type="text/javascript"></script>
    <script type="text/javascript">try{ clicky.init(101042100); }catch(e){}</script>
    <noscript><p><img alt="Clicky" width="1" height="1" src="//in.getclicky.com/101042100ns.gif" /></p></noscript>
  <% end %>
</body>
</html>